version: "3"

services:
  abitly_services:
    image: balexisnava/abitly-services
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: abitly
      POSTGRES_PASSWORD: abitly2019
      POSTGRES_DB: abitlydb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~